import { TripState } from './types';

// Datos reales del viaje (Bogotá → Medellín → Cartagena → Barranquilla →
// Palomino → Santa Marta, 9 al 18 de octubre de 2026), tal como quedaron
// definidos en el prototipo de artefacto compartido por el organizador.
// Reemplaza los datos de ejemplo/ficticios usados durante el desarrollo.
//
// travelers/suggestions/loans arrancan vacíos a propósito: la app ya va a
// usarse con el grupo real, así que nadie debe aparecer "ya registrado"
// ni ver sugerencias o préstamos de mentira.
export const INITIAL_TRIP_STATE: TripState = {
  config: {
    tripName: 'Ruta Caribe',
    dates: '9 - 18 de Octubre 2026',
    cities: ['Bogotá', 'Medellín', 'Cartagena', 'Barranquilla', 'Palomino', 'Santa Marta'],
    autoApprovePolls: false,
  },
  travelers: [],
  itinerary: [
    {
      dayNumber: 1,
      date: 'Viernes 9 de Octubre',
      isoDate: '2026-10-09',
      city: 'Bogotá',
      title: 'Salida nocturna a Medellín',
      tagline: 'Arranca el viaje: bus nocturno hacia Medellín',
      lodging: '— (se viaja de noche, sin hospedaje esta noche)',
      transport: 'Bus nocturno Bogotá → Medellín, ≈ $200.000 por persona. Terminal y hora exacta por confirmar.',
      estimatedBudgetCOP: 200000,
      activities: [
        { id: 'act-1-1', time: 'Noche', title: 'Bus nocturno a Medellín', description: 'Salimos de Bogotá en bus hacia Medellín (≈ $100.000–200.000 por persona, según fuente).', category: 'transporte', costEstimateCOP: 200000, location: 'Terminal de Bogotá' },
        { id: 'act-1-2', time: '', title: 'Comprar tiquetes con tiempo', description: 'Terminal y hora exacta por confirmar. Es el arranque del puente festivo: conviene comprar ya.', category: 'transporte' },
      ],
    },
    {
      dayNumber: 2,
      date: 'Sábado 10 de Octubre',
      isoDate: '2026-10-10',
      city: 'Medellín',
      title: 'Llegada a Medellín y Comuna 13',
      tagline: 'Comuna 13 de día, EDC o Provenza de noche',
      lodging: 'Airbnb en Medellín (2 noches, ≈ $90.000 por persona/noche — por reservar).',
      transport: 'Llegada en bus entre 7:00 y 8:00 a.m.',
      estimatedBudgetCOP: 180000,
      activities: [
        { id: 'act-2-1', time: '7:00–8:00', title: 'Llegada a Medellín', description: 'Llegamos a Medellín.', category: 'transporte' },
        { id: 'act-2-2', time: 'Mañana', title: 'Check-in en el Airbnb', description: 'Dejamos las maletas en el Airbnb.', category: 'hospedaje', costEstimateCOP: 90000, location: 'Medellín' },
        { id: 'act-2-3', time: 'Día', title: 'Comuna 13', description: 'Todos: recorrido por la Comuna 13.', category: 'visita', location: 'Comuna 13' },
        { id: 'act-2-4', time: 'Noche', title: 'EDC o Provenza', description: 'Quienes vayan al festival EDC, van al EDC. El resto sale a Provenza.', category: 'rumba', location: 'El Poblado' },
      ],
    },
    {
      dayNumber: 3,
      date: 'Domingo 11 de Octubre',
      isoDate: '2026-10-11',
      city: 'Medellín',
      title: 'OAPP o Medellín a tu ritmo',
      tagline: 'Cada quien elige su plan: festival OAPP o ciudad libre',
      lodging: 'Airbnb en Medellín (misma reserva del día anterior).',
      transport: '—',
      estimatedBudgetCOP: 60000,
      activities: [
        { id: 'act-3-1', time: 'Día', title: 'OAPP (opcional)', description: 'Quienes quieran ir a OAPP, van. Confirmar boletas y transporte.', category: 'rumba', location: 'Medellín' },
        { id: 'act-3-2', time: 'Día', title: 'Medellín a tu ritmo', description: 'El resto se queda conociendo Medellín (Plaza Botero, Museo de Antioquia, o excursión a Guatapé si hay tiempo).', category: 'visita', location: 'Medellín' },
      ],
    },
    {
      dayNumber: 4,
      date: 'Lunes 12 de Octubre',
      isoDate: '2026-10-12',
      city: 'Cartagena',
      title: 'Vuelo a Cartagena (lunes festivo)',
      tagline: 'Check-in en Getsemaní y tarde libre',
      lodging: 'Airbnb en Cartagena, check-in lunes / check-out miércoles 11:00 (≈ $120.000 por persona/noche — por reservar).',
      transport: 'Vuelo Medellín → Cartagena, ≈ $250.000 por persona. Hoy es festivo: comprar con tiempo.',
      estimatedBudgetCOP: 370000,
      activities: [
        { id: 'act-4-1', time: 'Mediodía', title: 'Vuelo a Cartagena', description: 'Salimos hacia Cartagena (tiquete ≈ $250.000 por persona). Ojo: hoy es festivo (12 de octubre), compra los tiquetes con tiempo.', category: 'transporte', costEstimateCOP: 250000 },
        { id: 'act-4-2', time: 'Mediodía', title: 'Check-in en el Airbnb', description: 'Llegamos y hacemos el check-in en el Airbnb apenas lo entreguen.', category: 'hospedaje', costEstimateCOP: 120000 },
        { id: 'act-4-3', time: 'Tarde', title: 'Tarde libre', description: 'Resto del día libre.', category: 'visita' },
      ],
    },
    {
      dayNumber: 5,
      date: 'Martes 13 de Octubre',
      isoDate: '2026-10-13',
      city: 'Cartagena',
      title: 'Día libre en Cartagena',
      tagline: 'Islas del Rosario, Playa Blanca o centro histórico — se decide en Votar',
      lodging: 'Airbnb en Cartagena (misma reserva).',
      transport: '—',
      estimatedBudgetCOP: 120000,
      activities: [
        { id: 'act-5-1', time: 'Todo el día', title: 'Día libre — se define en el grupo', description: 'Día libre. Lo definimos entre todos: Islas del Rosario, Playa Blanca (Barú), o centro histórico y Getsemaní. Mira la encuesta en la pestaña Votar.', category: 'naturaleza' },
      ],
    },
    {
      dayNumber: 6,
      date: 'Miércoles 14 de Octubre',
      isoDate: '2026-10-14',
      city: 'Barranquilla',
      title: 'Cartagena → Barranquilla',
      tagline: 'Malecón, Rueda Panorámica y rumba',
      lodging: 'Hotel en Barranquilla, 1 noche, ≈ $145.000 por persona (dato confirmado del grupo).',
      transport: 'Bus Cartagena → Barranquilla tras el check-out (11:00), ≈ $30.000 por persona (estimado, ~2 horas).',
      estimatedBudgetCOP: 220000,
      activities: [
        { id: 'act-6-1', time: '11:00', title: 'Check-out y salida a Barranquilla', description: 'Check-out en Cartagena y salida hacia Barranquilla.', category: 'transporte', costEstimateCOP: 30000 },
        { id: 'act-6-2', time: 'Tarde', title: 'Check-in en el hotel', description: 'Llegamos al hotel (≈ $145.000 por persona la noche).', category: 'hospedaje', costEstimateCOP: 145000 },
        { id: 'act-6-3', time: 'Almuerzo', title: 'Almuerzo y primer vistazo a la ciudad', description: 'Almorzar y conocer Barranquilla.', category: 'comida' },
        { id: 'act-6-4', time: 'Tarde–noche', title: 'Malecón del Río', description: 'Malecón: la Rueda Panorámica y los monumentos.', category: 'visita', location: 'Gran Malecón del Río' },
        { id: 'act-6-5', time: 'Noche', title: 'Rumba en Barranquilla', description: 'A rumbear (zona de la Calle 84 y alrededores).', category: 'rumba' },
      ],
    },
    {
      dayNumber: 7,
      date: 'Jueves 15 de Octubre',
      isoDate: '2026-10-15',
      city: 'Palomino',
      title: 'Rumbo a Palomino',
      tagline: 'Playa, hostales y fiesta de pueblo',
      lodging: 'Hostales en Palomino, 2 noches, ≈ $65.000 por persona/noche (rango $50.000–80.000).',
      transport: 'Bus Barranquilla → Palomino, ≈ $55.000 por persona (estimado, normalmente vía Santa Marta).',
      estimatedBudgetCOP: 190000,
      activities: [
        { id: 'act-7-1', time: 'Mediodía', title: 'Bus a Palomino', description: 'Salimos hacia Palomino.', category: 'transporte', costEstimateCOP: 55000 },
        { id: 'act-7-2', time: 'Tarde', title: 'Check-in en los hostales', description: 'Nos instalamos en los hostales (≈ $50.000–80.000 la noche).', category: 'hospedaje', costEstimateCOP: 65000 },
        { id: 'act-7-3', time: 'Noche', title: 'Pueblo y fiesta', description: 'Conocer el pueblo y fiesta.', category: 'rumba', location: 'Palomino' },
      ],
    },
    {
      dayNumber: 8,
      date: 'Viernes 16 de Octubre',
      isoDate: '2026-10-16',
      city: 'Palomino',
      title: 'Parque Tayrona',
      tagline: 'Playas y senderos — salida muy temprano',
      lodging: 'Hostales en Palomino (misma reserva).',
      transport: '—',
      estimatedBudgetCOP: 65000,
      activities: [
        { id: 'act-8-1', time: 'Muy temprano', title: 'Salida al Parque Tayrona', description: 'Salimos hacia el Parque Tayrona. Acceso principal por El Zaino, sobre la troncal del Caribe. Llevar documento y efectivo.', category: 'transporte' },
        { id: 'act-8-2', time: '', title: 'Entrada 2026', description: 'Colombianos y residentes ≈ $36.500–43.000; extranjeros ≈ $81.000–96.500 según temporada.', category: 'naturaleza', costEstimateCOP: 43000 },
        { id: 'act-8-3', time: 'Todo el día', title: 'Playas y senderos', description: 'Playas y senderos del parque.', category: 'naturaleza', location: 'Parque Tayrona' },
        { id: 'act-8-4', time: 'Noche', title: 'Regreso a Palomino', description: 'Volvemos a Palomino a descansar. Ojo: el parque cierra unos días al año por ceremonias indígenas (en otros años, del 19 de octubre al 2 de noviembre) — confirmar fechas 2026 antes de reservar.', category: 'hospedaje' },
      ],
    },
    {
      dayNumber: 9,
      date: 'Sábado 17 de Octubre',
      isoDate: '2026-10-17',
      city: 'Santa Marta',
      title: 'Palomino → Santa Marta',
      tagline: 'Última noche de rumba para quienes se quedan',
      lodging: 'Alojamiento en Santa Marta, 1 noche, ≈ $70.000 por persona (solo para quienes se quedan el sábado).',
      transport: 'Bus Palomino → Santa Marta, ≈ $20.000 por persona (estimado, entre $13.000 y $24.000 según empresa).',
      estimatedBudgetCOP: 90000,
      activities: [
        { id: 'act-9-1', time: 'Temprano', title: 'Bus a Santa Marta', description: 'Volvemos a Santa Marta.', category: 'transporte', costEstimateCOP: 20000 },
        { id: 'act-9-2', time: 'Día', title: 'Quien deba irse, se va', description: 'Quienes tengan que irse ese día, se van. Los demás nos quedamos la noche.', category: 'transporte' },
        { id: 'act-9-3', time: 'Noche', title: 'Rumba en Santa Marta', description: 'Rumba en Santa Marta (centro histórico).', category: 'rumba', location: 'Santa Marta' },
      ],
    },
    {
      dayNumber: 10,
      date: 'Domingo 18 de Octubre',
      isoDate: '2026-10-18',
      city: 'Santa Marta',
      title: 'Regreso a Bogotá',
      tagline: 'Cierra la aventura — vuelo de vuelta a Bogotá',
      lodging: '—',
      transport: 'Vuelo Santa Marta → Bogotá, ≈ $250.000 por persona (por confirmar).',
      estimatedBudgetCOP: 250000,
      activities: [
        { id: 'act-10-1', time: 'Día', title: 'Vuelo de regreso a Bogotá', description: 'La mayoría vuelve a Bogotá (avión ≈ $250.000, por confirmar).', category: 'transporte', costEstimateCOP: 250000 },
      ],
    },
  ],
  places: [
    { id: 'pl1', city: 'Medellín', name: 'Comuna 13', category: 'cultura', description: 'Recorrido por sus murales, escaleras eléctricas y grafitis. Está en el plan del sábado.', lat: 6.2557, lng: -75.59 },
    { id: 'pl2', city: 'Medellín', name: 'Provenza', category: 'rumba', description: 'Zona de bares y restaurantes en El Poblado. Plan de noche para quienes no van al festival.' },
    { id: 'pl3', city: 'Medellín', name: 'Festival EDC', category: 'evento', description: 'Sábado 10 de octubre, para quienes vayan. Confirmar boletas y transporte.' },
    { id: 'pl4', city: 'Medellín', name: 'OAPP', category: 'evento', description: 'Domingo 11 de octubre, para quienes vayan. Confirmar boletas y transporte.' },
    { id: 'pl5', city: 'Medellín', name: 'Plaza Botero y Museo de Antioquia', category: 'cultura', description: 'Idea para el domingo, para quienes se quedan en la ciudad.' },
    { id: 'pl6', city: 'Medellín', name: 'Guatapé', category: 'naturaleza', description: 'Idea de excursión de un día si quedan ganas y tiempo.', lat: 6.2322, lng: -75.159 },
    { id: 'pl7', city: 'Cartagena', name: 'Centro histórico amurallado', category: 'imperdible', description: 'Calles coloniales, plazas y las murallas.', lat: 10.4236, lng: -75.5518 },
    { id: 'pl8', city: 'Cartagena', name: 'Getsemaní', category: 'rumba', description: 'Murales, comida y bares. Buen plan para la noche.', lat: 10.4231, lng: -75.5495 },
    { id: 'pl9', city: 'Cartagena', name: 'Castillo San Felipe de Barajas', category: 'cultura', description: 'La fortaleza más grande de la ciudad.', lat: 10.4227, lng: -75.5389 },
    { id: 'pl10', city: 'Cartagena', name: 'Islas del Rosario / Playa Blanca (Barú)', category: 'naturaleza', description: 'Opción para el martes libre (mira la votación).' },
    { id: 'pl11', city: 'Barranquilla', name: 'Gran Malecón del Río', category: 'imperdible', description: 'Paseo junto al río Magdalena, con la Rueda Panorámica.', lat: 10.9878, lng: -74.7847 },
    { id: 'pl12', city: 'Barranquilla', name: 'Rueda Panorámica', category: 'imperdible', description: 'Plan de tarde-noche en el malecón.', lat: 10.9878, lng: -74.7847 },
    { id: 'pl13', city: 'Barranquilla', name: 'Monumentos del Malecón', category: 'cultura', description: 'Los monumentos del paseo. Van en el plan de la tarde-noche.' },
    { id: 'pl14', city: 'Barranquilla', name: 'Zona de rumba (Calle 84 y alrededores)', category: 'rumba', description: 'Para salir de fiesta después del malecón.' },
    { id: 'pl15', city: 'Palomino', name: 'Playa de Palomino', category: 'naturaleza', description: 'Playa larga y tranquila, buena para descansar.', lat: 11.2554, lng: -73.5586 },
    { id: 'pl16', city: 'Palomino', name: 'Río Palomino en tubing', category: 'naturaleza', description: 'Bajar el río en neumático. Idea para la tarde.' },
    { id: 'pl17', city: 'Palomino', name: 'Parque Tayrona', category: 'imperdible', description: 'Viernes 16 muy temprano. El acceso principal es El Zaino, sobre la troncal del Caribe. Llevar documento y efectivo.', lat: 11.3187, lng: -73.907 },
    { id: 'pl18', city: 'Palomino', name: 'Rumba en los hostales y bares del pueblo', category: 'rumba', description: 'Planes de noche en Palomino.' },
    { id: 'pl19', city: 'Santa Marta', name: 'Centro histórico y bahía', category: 'cultura', description: 'Caminata corta antes de la noche.', lat: 11.2404, lng: -74.211 },
    { id: 'pl20', city: 'Santa Marta', name: 'Playa Salguero o El Rodadero', category: 'naturaleza', description: 'Para quienes lleguen temprano el sábado.' },
    { id: 'pl21', city: 'Santa Marta', name: 'Rumba en el centro', category: 'rumba', description: 'Plan de noche para quienes se quedan el sábado.' },
  ],
  announcements: [
    { id: 'a1', text: 'Bienvenidos. Aquí está el plan del 9 al 18 de octubre. Sugieran ideas, voten y anoten las cuentas para que nadie se quede sin voz.', createdAt: '2026-09-21T13:30:00.000Z' },
    { id: 'a2', text: 'El lunes 12 de octubre es festivo: buses y vuelos se llenan. Conviene comprar los tiquetes ya.', createdAt: '2026-09-21T13:31:00.000Z' },
    { id: 'a3', text: 'Parque Tayrona: hay que confirmar que no esté cerrado por ceremonias indígenas el 16 de octubre.', createdAt: '2026-09-21T13:32:00.000Z' },
  ],
  lodging: [
    { id: 'l1', city: 'Medellín', name: 'Airbnb en Medellín', fromDate: '2026-10-10', toDate: '2026-10-12', pricePerNightCOP: 90000, isEstimated: true, notes: 'Por reservar. Llegamos a dejar maletas el sábado en la mañana.' },
    { id: 'l2', city: 'Cartagena', name: 'Airbnb en Cartagena', fromDate: '2026-10-12', toDate: '2026-10-14', pricePerNightCOP: 120000, isEstimated: true, notes: 'Check-in apenas lo entreguen el lunes; check-out a las 11:00 el miércoles.' },
    { id: 'l3', city: 'Barranquilla', name: 'Hotel en Barranquilla', fromDate: '2026-10-14', toDate: '2026-10-15', pricePerNightCOP: 145000, isEstimated: false, notes: 'Precio que llevamos hasta ahora.' },
    { id: 'l4', city: 'Palomino', name: 'Hostales en Palomino', fromDate: '2026-10-15', toDate: '2026-10-17', pricePerNightCOP: 65000, isEstimated: false, notes: 'Rango de $50.000 a $80.000 la noche; usamos el punto medio.' },
    { id: 'l5', city: 'Santa Marta', name: 'Alojamiento en Santa Marta', fromDate: '2026-10-17', toDate: '2026-10-18', pricePerNightCOP: 70000, isEstimated: true, notes: 'Solo para quienes se quedan el sábado.' },
  ],
  transportLegs: [
    { id: 't1', fromCity: 'Bogotá', toCity: 'Medellín', date: '2026-10-09', time: 'Noche', mode: 'bus', priceCOP: 200000, isEstimated: false, colorCity: 'med', notes: 'Bus nocturno. Llegamos entre 7:00 y 8:00 de la mañana.' },
    { id: 't2', fromCity: 'Medellín', toCity: 'Cartagena', date: '2026-10-12', time: 'Mediodía', mode: 'vuelo', priceCOP: 250000, isEstimated: false, colorCity: 'ctg', notes: 'Tiquete aproximado que llevamos. Es festivo: comprar con tiempo.' },
    { id: 't3', fromCity: 'Cartagena', toCity: 'Barranquilla', date: '2026-10-14', time: 'Después del check-out (11:00)', mode: 'bus', priceCOP: 30000, isEstimated: true, colorCity: 'baq', notes: 'Estimado. Bus directo de unas 2 horas.' },
    { id: 't4', fromCity: 'Barranquilla', toCity: 'Palomino', date: '2026-10-15', time: 'Mediodía', mode: 'bus', priceCOP: 55000, isEstimated: true, colorCity: 'pal', notes: 'Estimado. Normalmente con paso por Santa Marta.' },
    { id: 't5', fromCity: 'Palomino', toCity: 'Santa Marta', date: '2026-10-17', time: 'Temprano', mode: 'bus', priceCOP: 20000, isEstimated: true, colorCity: 'smr', notes: 'Estimado. Entre $13.000 y $24.000 según empresa.' },
    { id: 't6', fromCity: 'Santa Marta', toCity: 'Bogotá', date: '2026-10-18', time: 'Por definir', mode: 'vuelo', priceCOP: 250000, isEstimated: true, colorCity: 'bog', notes: 'Estimado; los precios varían mucho según cuándo se compre.' },
  ],
  suggestions: [],
  polls: [
    {
      id: 'p1',
      question: '¿Quién va al EDC el sábado 10?',
      createdBy: 'Organizador',
      creatorRole: 'admin',
      status: 'activa',
      createdAt: '2026-09-21T13:30:00.000Z',
      options: [
        { id: 'opt-p1-a', text: 'Voy al EDC', votes: [] },
        { id: 'opt-p1-b', text: 'Me voy a Provenza', votes: [] },
        { id: 'opt-p1-c', text: 'Aún no sé', votes: [] },
      ],
    },
    {
      id: 'p2',
      question: 'Domingo 11: ¿OAPP o Medellín?',
      createdBy: 'Organizador',
      creatorRole: 'admin',
      status: 'activa',
      createdAt: '2026-09-21T13:30:00.000Z',
      options: [
        { id: 'opt-p2-a', text: 'Voy a OAPP', votes: [] },
        { id: 'opt-p2-b', text: 'Me quedo conociendo Medellín', votes: [] },
        { id: 'opt-p2-c', text: 'Aún no sé', votes: [] },
      ],
    },
    {
      id: 'p3',
      question: 'Martes 13 en Cartagena, ¿qué hacemos?',
      createdBy: 'Organizador',
      creatorRole: 'admin',
      status: 'activa',
      createdAt: '2026-09-21T13:30:00.000Z',
      options: [
        { id: 'opt-p3-a', text: 'Islas del Rosario', votes: [] },
        { id: 'opt-p3-b', text: 'Playa Blanca (Barú)', votes: [] },
        { id: 'opt-p3-c', text: 'Centro histórico y Getsemaní', votes: [] },
        { id: 'opt-p3-d', text: 'Día libre', votes: [] },
      ],
    },
  ],
  loans: [],
};
