import { TripState } from './types';

export const INITIAL_TRIP_STATE: TripState = {
  config: {
    tripName: 'Medellín - Caribe 2026',
    dates: '9 - 18 de Octubre',
    cities: ['Medellín', 'Cartagena', 'Barranquilla', 'Palomino', 'Santa Marta'],
    autoApprovePolls: false,
  },
  travelers: [
    { id: 'usr-1', name: 'Mateo (Líder)', avatar: '🌴', joinedAt: '2026-10-01T10:00:00Z' },
    { id: 'usr-2', name: 'Valentina', avatar: '🌺', joinedAt: '2026-10-01T11:15:00Z' },
    { id: 'usr-3', name: 'Andrés P.', avatar: '☕', joinedAt: '2026-10-01T14:30:00Z' },
    { id: 'usr-4', name: 'Sofía', avatar: '🌊', joinedAt: '2026-10-02T09:20:00Z' },
    { id: 'usr-5', name: 'Carlos R.', avatar: '🧗', joinedAt: '2026-10-02T16:45:00Z' },
    { id: 'usr-6', name: 'Camila S.', avatar: '🦜', joinedAt: '2026-10-03T08:10:00Z' },
  ],
  itinerary: [
    {
      dayNumber: 1,
      date: 'Viernes 9 de Octubre',
      isoDate: '2026-10-09',
      city: 'Medellín',
      title: 'Llegada a la Ciudad de la Eterna Primavera',
      tagline: 'Check-in, café de especialidad y noche en El Poblado',
      lodging: 'Hotel Selina Medellín / Airbnb El Poblado',
      lodgingNotes: 'Calle 10 con Cra 43D. Desayuno incluido. Check-in desde las 3:00 PM.',
      transport: 'Vuelos individuales al Aeropuerto JMC (MDE) + Van compartida a El Poblado.',
      estimatedBudgetCOP: 180000,
      activities: [
        {
          id: 'act-101',
          time: '11:00 AM - 02:00 PM',
          title: 'Recepción y almuerzo paisa de bienvenida',
          description: 'Encuentro de todos en Café Velvet / Restaurante Mondongos El Poblado.',
          category: 'comida',
          costEstimateCOP: 45000,
          location: 'El Poblado',
        },
        {
          id: 'act-102',
          time: '03:30 PM - 06:30 PM',
          title: 'Tour Comuna 13 & Grafiti',
          description: 'Escaleras eléctricas, muestras de hip hop y degustación de helados de mango biche.',
          category: 'visita',
          costEstimateCOP: 35000,
          location: 'Comuna 13',
        },
        {
          id: 'act-103',
          time: '08:30 PM',
          title: 'Rooftop & Cena grupal en Provenza',
          description: 'Cócteles de bienvenida en Envy Rooftop y picadas en Provenza.',
          category: 'rumba',
          costEstimateCOP: 80000,
          location: 'Provenza, El Poblado',
        },
      ],
    },
    {
      dayNumber: 2,
      date: 'Sábado 10 de Octubre',
      isoDate: '2026-10-10',
      city: 'Medellín',
      title: 'Piedra del Peñol, Guatapé y Vuelo a la Costa',
      tagline: 'Ascenso a la gran roca, zócalos de colores y vuelo a Cartagena',
      lodging: 'Hotel Casa de las Palmas / Airbnb Getsemaní (Cartagena)',
      lodgingNotes: 'Check-in nocturno al llegar a Cartagena.',
      transport: 'Chiva/Van turística a Guatapé (ida y vuelta) + Vuelo Medellín (MDE) -> Cartagena (CTG) a las 8:00 PM.',
      estimatedBudgetCOP: 260000,
      activities: [
        {
          id: 'act-201',
          time: '07:00 AM - 01:00 PM',
          title: 'Subida a la Piedra del Peñol & Barco en la Represa',
          description: '740 escalones con vista panorámica inolvidable + paseo en lancha.',
          category: 'naturaleza',
          costEstimateCOP: 65000,
          location: 'Guatapé',
        },
        {
          id: 'act-202',
          time: '01:30 PM - 04:00 PM',
          title: 'Pueblito de Guatapé y almuerzo de trucha',
          description: 'Plaza de los Zócalos y calle del recuerdo.',
          category: 'comida',
          costEstimateCOP: 45000,
          location: 'Guatapé centro',
        },
        {
          id: 'act-203',
          time: '07:30 PM - 09:30 PM',
          title: 'Vuelo a Cartagena & Primer golpe de brisa caribeña',
          description: 'Llegada al Aeropuerto Rafael Núñez y traslado a Getsemaní.',
          category: 'transporte',
          costEstimateCOP: 150000,
          location: 'Aeropuerto CTG -> Getsemaní',
        },
      ],
    },
    {
      dayNumber: 3,
      date: 'Domingo 11 de Octubre',
      isoDate: '2026-10-11',
      city: 'Cartagena',
      title: 'Magia Colonial en el Corralito de Piedra',
      tagline: 'Castillo San Felipe, murallas, atardecer y rumba caribeña',
      lodging: 'Hotel en Getsemaní, Cartagena',
      transport: 'A pie por el centro histórico y taxis grupales.',
      estimatedBudgetCOP: 210000,
      activities: [
        {
          id: 'act-301',
          time: '09:00 AM - 11:30 AM',
          title: 'Castillo de San Felipe de Barajas',
          description: 'Recorrido por los túneles y murallas de la fortaleza militar española.',
          category: 'visita',
          costEstimateCOP: 35000,
          location: 'San Felipe',
        },
        {
          id: 'act-302',
          time: '01:00 PM - 03:30 PM',
          title: 'Almuerzo de cazuela de mariscos & limonada de coco',
          description: 'Gastronomía tradicional en el Mercado de Bazurto o restaurante El Arsenal.',
          category: 'comida',
          costEstimateCOP: 55000,
          location: 'Centro Histórico',
        },
        {
          id: 'act-303',
          time: '05:00 PM - 07:00 PM',
          title: 'Atardecer sobre las murallas en Café del Mar',
          description: 'Música chillout, brisa del mar caribe y vista del sol poniente.',
          category: 'visita',
          costEstimateCOP: 50000,
          location: 'Baluarte de Santo Domingo',
        },
        {
          id: 'act-304',
          time: '09:30 PM - 02:00 AM',
          title: 'Plaza de la Trinidad y salsa en Café Havana',
          description: 'Noche cultural en Getsemaní con mojitos y música en vivo.',
          category: 'rumba',
          costEstimateCOP: 70000,
          location: 'Getsemaní',
        },
      ],
    },
    {
      dayNumber: 4,
      date: 'Lunes 12 de Octubre',
      isoDate: '2026-10-12',
      city: 'Cartagena',
      title: 'Islas del Rosario & Aguas Turquesas',
      tagline: 'Día completo de lancha rápida, snorkel en arrecife y Playa Blanca / Cholón',
      lodging: 'Hotel en Getsemaní, Cartagena',
      transport: 'Lancha rápida privada ida y vuelta desde el muelle de La Bodeguita.',
      estimatedBudgetCOP: 290000,
      activities: [
        {
          id: 'act-401',
          time: '08:00 AM - 02:00 PM',
          title: 'Tour en lancha por Islas del Rosario + Snorkel',
          description: 'Parada en Isla Grande, snorkel en avioneta sumergida y club de playa.',
          category: 'playa',
          costEstimateCOP: 180000,
          location: 'Parque Nacional Corales del Rosario',
        },
        {
          id: 'act-402',
          time: '02:30 PM - 05:00 PM',
          title: 'Tarde de playa y fiesta en Cholón o Barú',
          description: 'Almuerzo con pargo frito, patacones con suero y coco loco.',
          category: 'playa',
          costEstimateCOP: 65000,
          location: 'Cholón / Barú',
        },
      ],
    },
    {
      dayNumber: 5,
      date: 'Martes 13 de Octubre',
      isoDate: '2026-10-13',
      city: 'Barranquilla',
      title: 'Rumbo a la Arenosa: Barranquilla y el Río Magdalena',
      tagline: 'Malecón del Río, Aleta del Tiburón y gastronomía costera',
      lodging: 'Hotel Prado / Alto Prado Barranquilla',
      transport: 'Expreso Brasilia o Van privada Cartagena -> Barranquilla (2.5 horas).',
      estimatedBudgetCOP: 160000,
      activities: [
        {
          id: 'act-501',
          time: '09:00 AM - 11:30 AM',
          title: 'Ruta costera Cartagena -> Barranquilla',
          description: 'Paisajes de ciénagas y mar Caribe por la Vía al Mar.',
          category: 'transporte',
          costEstimateCOP: 35000,
          location: 'Ruta Vía al Mar',
        },
        {
          id: 'act-502',
          time: '01:00 PM - 03:00 PM',
          title: 'Almuerzo en Narcobollo / Caimán del Río',
          description: 'Arepa de huevo de Luruaco, bollo limpio y butifarra soledeña.',
          category: 'comida',
          costEstimateCOP: 40000,
          location: 'Caimán del Río',
        },
        {
          id: 'act-503',
          time: '04:30 PM - 08:00 PM',
          title: 'Gran Malecón del Río y Monumento La Ventana al Mundo',
          description: 'Paseo al lado del río Magdalena viendo atardecer y foto icónica en la Aleta del Tiburón.',
          category: 'visita',
          costEstimateCOP: 30000,
          location: 'Gran Malecón del Río',
        },
      ],
    },
    {
      dayNumber: 6,
      date: 'Miércoles 14 de Octubre',
      isoDate: '2026-10-14',
      city: 'Santa Marta',
      title: 'La Perla de América y Bahía Histórica',
      tagline: 'El Rodadero, Centro Histórico de Santa Marta y atardecer en la Marina',
      lodging: 'Hotel Boutique Casa Marina / Calle 17 Centro Histórico',
      transport: 'Van privada Barranquilla -> Santa Marta cruzando el Puente Pumarejo (1.5 horas).',
      estimatedBudgetCOP: 175000,
      activities: [
        {
          id: 'act-601',
          time: '10:00 AM - 12:00 PM',
          title: 'Traslado Barranquilla a Santa Marta',
          description: 'Cruce del Parque Isla Salamanca y llegada a la ciudad más antigua de Colombia.',
          category: 'transporte',
          costEstimateCOP: 30000,
          location: 'Carretera Barranquilla - Santa Marta',
        },
        {
          id: 'act-602',
          time: '02:00 PM - 05:00 PM',
          title: 'Paseo por la Bahía de Santa Marta y Quinta de San Pedro',
          description: 'Caminata por el camellón Rodrigo de Bastidas y museo histórico.',
          category: 'visita',
          costEstimateCOP: 35000,
          location: 'Centro Histórico Santa Marta',
        },
        {
          id: 'act-603',
          time: '06:00 PM - 09:30 PM',
          title: 'Cena y coctelería en el Parque de los Novios',
          description: 'Ambiente bohemio y gastronomía caribeña.',
          category: 'comida',
          costEstimateCOP: 60000,
          location: 'Parque de los Novios',
        },
      ],
    },
    {
      dayNumber: 7,
      date: 'Jueves 15 de Octubre',
      isoDate: '2026-10-15',
      city: 'Santa Marta',
      title: 'Expedición Épica al Parque Nacional Natural Tayrona',
      tagline: 'Caminata selvática, Cañaveral, Arrecifes, La Piscina y Cabo San Juan de Guía',
      lodging: 'Hotel en Santa Marta / Posada ecológica cerca a El Zaino',
      transport: 'Buseta grupal a la entrada del Zaino (Tayrona) y caminata ecológica.',
      estimatedBudgetCOP: 220000,
      activities: [
        {
          id: 'act-701',
          time: '06:30 AM - 11:30 AM',
          title: 'Entrada al Tayrona y trekking selvático',
          description: 'Caminata entre bosque húmedo tropical, puentes de madera y sonidos de monos aulladores.',
          category: 'naturaleza',
          costEstimateCOP: 85000,
          location: 'PNN Tayrona (El Zaino -> Arrecifes)',
        },
        {
          id: 'act-702',
          time: '12:00 PM - 03:30 PM',
          title: 'Baño en La Piscina y llegada al Cabo San Juan',
          description: 'La foto postal con el quiosco sobre el peñasco y aguas cristalinas.',
          category: 'playa',
          costEstimateCOP: 50000,
          location: 'Cabo San Juan de Guía',
        },
        {
          id: 'act-703',
          time: '04:00 PM - 06:30 PM',
          title: 'Regreso a caballo o a pie al atardecer',
          description: 'Opción de rentar caballo o caminata suave hacia la salida.',
          category: 'naturaleza',
          costEstimateCOP: 45000,
          location: 'PNN Tayrona',
        },
      ],
    },
    {
      dayNumber: 8,
      date: 'Viernes 16 de Octubre',
      isoDate: '2026-10-16',
      city: 'Palomino',
      title: 'Vibras Místicas de Palomino y el Tubing en el Río',
      tagline: 'Donde la Sierra Nevada desemboca en el Mar Caribe',
      lodging: 'Eco-Hostel / Glamping frente al mar en Palomino',
      lodgingNotes: 'Cabañas rústicas con hamacas y acceso directo a la playa.',
      transport: 'Van privada desde Santa Marta hasta Palomino, La Guajira (1.5 horas).',
      estimatedBudgetCOP: 190000,
      activities: [
        {
          id: 'act-801',
          time: '10:30 AM - 01:30 PM',
          title: 'Aventura de Tubing por el Río Palomino',
          description: 'Subida en mototaxi + 30 min caminata y descenso flotando en neumático gigante hasta desembocar en el mar.',
          category: 'naturaleza',
          costEstimateCOP: 55000,
          location: 'Río Palomino',
        },
        {
          id: 'act-802',
          time: '02:30 PM - 05:30 PM',
          title: 'Tarde de playa, surf y jugos naturales exóticos',
          description: 'Jugos de corozo, maracuyá y coco frente al oleaje.',
          category: 'playa',
          costEstimateCOP: 35000,
          location: 'Playa de Palomino',
        },
        {
          id: 'act-803',
          time: '07:30 PM - 11:30 PM',
          title: 'Cena con pizzas artesanales y fogata bajo las estrellas',
          description: 'Fogata en la playa con guitarra, tambores y relatos del viaje.',
          category: 'rumba',
          costEstimateCOP: 50000,
          location: 'Playa de Palomino',
        },
      ],
    },
    {
      dayNumber: 9,
      date: 'Sábado 17 de Octubre',
      isoDate: '2026-10-17',
      city: 'Palomino',
      title: 'Cascadas de Quebrada Valencia y Despedida Caribeña',
      tagline: 'Pozos naturales de agua dulce, compras artesanales Wayuu y noche final',
      lodging: 'Eco-Hostel en Palomino',
      transport: 'Transporte local en Jeep / moto chiva.',
      estimatedBudgetCOP: 165000,
      activities: [
        {
          id: 'act-901',
          time: '09:00 AM - 01:00 PM',
          title: 'Cascadas y pozos de Quebrada Valencia',
          description: 'Caminata entre árboles gigantes hasta pozas de agua fresca que bajan de la Sierra.',
          category: 'naturaleza',
          costEstimateCOP: 25000,
          location: 'Quebrada Valencia',
        },
        {
          id: 'act-902',
          time: '03:00 PM - 06:00 PM',
          title: 'Feria de artesanías locales y mochilas Wayuu',
          description: 'Comprar recuerdos, mochilas auténticas y pulseras.',
          category: 'visita',
          costEstimateCOP: 60000,
          location: 'Calle principal de Palomino',
        },
        {
          id: 'act-903',
          time: '08:00 PM - 01:00 AM',
          title: 'Gran Fiesta y Cena de Cierre del Grupo',
          description: 'Brindis de agradecimiento por los 10 días de aventura, música en vivo y fiesta de despedida.',
          category: 'rumba',
          costEstimateCOP: 80000,
          location: 'Sua Restaurante & Bar Palomino',
        },
      ],
    },
    {
      dayNumber: 10,
      date: 'Domingo 18 de Octubre',
      isoDate: '2026-10-18',
      city: 'Santa Marta',
      title: 'Regreso y Cierre de la Aventura',
      tagline: 'Desayuno caribeño, traslado a aeropuerto y regreso a casa',
      lodging: 'Check-out final',
      transport: 'Van grupal Palomino -> Aeropuerto Simón Bolívar de Santa Marta (SMR) o Barranquilla.',
      estimatedBudgetCOP: 120000,
      activities: [
        {
          id: 'act-1001',
          time: '08:00 AM - 10:30 AM',
          title: 'Último desayuno frente al mar y fotos grupales',
          description: 'Huevos pericos, arepa de maíz blanco y café colombiano.',
          category: 'comida',
          costEstimateCOP: 30000,
          location: 'Palomino',
        },
        {
          id: 'act-1002',
          time: '11:00 AM - 03:00 PM',
          title: 'Traslado al Aeropuerto y liquidación final de cuentas',
          description: 'Abrazos, despedidas y cuadre de saldos en la app.',
          category: 'transporte',
          costEstimateCOP: 45000,
          location: 'Aeropuerto SMR',
        },
      ],
    },
  ],
  suggestions: [
    {
      id: 'sug-1',
      dayNumber: 3,
      city: 'Cartagena',
      proposerId: 'usr-2',
      proposerName: 'Valentina',
      title: 'Comer helado artesanal en Gelatería Tramonti',
      category: 'restaurante',
      description: 'Queda cerca de la Plaza de Bolívar en Cartagena, dicen que tienen helado de tamarindo y maracuyá insuperable.',
      estimatedCostCOP: 18000,
      status: 'pendiente',
      createdAt: '2026-10-02T14:15:00Z',
    },
    {
      id: 'sug-2',
      dayNumber: 4,
      city: 'Cartagena',
      proposerId: 'usr-3',
      proposerName: 'Andrés P.',
      title: 'Alquilar bote privado en lugar de tour masivo',
      category: 'transporte alterno',
      description: 'Si somos más de 8 personas, nos sale casi al mismo precio por cabeza y podemos elegir las islas que queramos.',
      estimatedCostCOP: 160000,
      status: 'aprobada',
      createdAt: '2026-10-02T16:00:00Z',
      adminNote: 'Aprobado: Mateo ya cotizó la lancha privada y queda reservada.',
    },
    {
      id: 'sug-3',
      dayNumber: 8,
      city: 'Palomino',
      proposerId: 'usr-4',
      proposerName: 'Sofía',
      title: 'Clase matutina de Yoga frente al mar',
      category: 'actividad',
      description: 'En el hostal Casa Sirena dan clases a las 7:00 AM con aporte voluntario.',
      estimatedCostCOP: 25000,
      status: 'pendiente',
      createdAt: '2026-10-03T10:30:00Z',
    },
  ],
  polls: [
    {
      id: 'poll-1',
      question: '¿A dónde vamos el domingo en Cartagena al atardecer?',
      description: 'Elijamos el plan principal para cerrar el día en el Centro Histórico.',
      createdBy: 'Mateo (Líder)',
      creatorRole: 'admin',
      status: 'activa',
      createdAt: '2026-10-02T12:00:00Z',
      options: [
        { id: 'opt-1', text: 'Café del Mar sobre las murallas clásicas', votes: ['Mateo (Líder)', 'Valentina', 'Sofía'] },
        { id: 'opt-2', text: 'Rooftop Movich con vista panorámica a la bahía', votes: ['Andrés P.', 'Carlos R.'] },
        { id: 'opt-3', text: 'Pícnic libre con cerveza en el baluarte Santo Domingo', votes: ['Camila S.'] },
      ],
    },
    {
      id: 'poll-2',
      question: '¿Alquiler de caballos para el retorno del Cabo San Juan (Tayrona)?',
      description: 'La caminata de vuelta es de 2 horas. ¿Hacemos trekking o contratamos caballos?',
      createdBy: 'Valentina',
      creatorRole: 'traveler',
      status: 'activa',
      createdAt: '2026-10-03T09:00:00Z',
      options: [
        { id: 'opt-201', text: 'Caminando tranquilos disfrutando la selva', votes: ['Mateo (Líder)', 'Sofía', 'Camila S.'] },
        { id: 'opt-202', text: 'Alquilar caballo para ir más relajados', votes: ['Valentina', 'Carlos R.'] },
      ],
    },
  ],
  loans: [
    {
      id: 'loan-1',
      lender: 'Mateo (Líder)',
      borrower: 'Andrés P.',
      amount: 45000,
      concept: 'Taxi compartido aeropuerto JMC a Medellín',
      createdAt: '2026-10-02T15:20:00Z',
      settled: false,
    },
    {
      id: 'loan-2',
      lender: 'Valentina',
      borrower: 'Sofía',
      amount: 32000,
      concept: 'Almuerzo típico en El Poblado',
      createdAt: '2026-10-02T18:40:00Z',
      settled: false,
    },
    {
      id: 'loan-3',
      lender: 'Andrés P.',
      borrower: 'Mateo (Líder)',
      amount: 20000,
      concept: 'Cervezas y picada en Provenza',
      createdAt: '2026-10-02T22:15:00Z',
      settled: false,
    },
    {
      id: 'loan-4',
      lender: 'Carlos R.',
      borrower: 'Camila S.',
      amount: 55000,
      concept: 'Abono reserva lancha Islas del Rosario',
      createdAt: '2026-10-03T11:00:00Z',
      settled: false,
    },
  ],
};
